#!/usr/bin/env python
"""
Fate & Fortune SMS.

Usage:
  fate <your_mobile_number> [--password=<pwd>]
  fate -h | --help

  The only parameter is your phone number preceded by the international
  dialing code +31 for the Netherlands.

Options:
  -h --help              Show this screen.
  -p --password=<pw>     Provide password.
"""
from twilio.rest import Client
from docopt import docopt
import json
from SimpleAES import SimpleAES  # military-grade bollocks!
import getpass

secret = """U2FsdGVkX19a88BWnbJa604wgw+S/s2ZtMhHPwgrfrfzd5g1dWB1iWuQFPm3gZXn
5i3qEE6dLoR8tB2UCna7AE2gjsOba4Q3kZCi8j+IzXXdM5U/oX/OACgeAbpyzv4u
XPoJgXI6o+PplqU75WpoBt+DwlKxPKAoytrd4kUdIcWMO2tcsZnYIM1yr3BWMhqe
UzufWBMNzoBoBV4vgNKEMA=="""

def decrypt_secret(passphrase="Haven't got a clue"):
#    try:
    aes = SimpleAES(passphrase)
    dekret = aes.decrypt(secret) #aes.decrypt(secret)
    return json.loads(dekret)
#    except Exception as e:
#        print("(!!!) Damn! That was not the right password! Quick! Let's not waste precious time! Try again.")

def send_sms_to(mobile, sid, token):
    try:
        client = Client(sid, token)
        myTwilioNumber = '+31852080387'
        msgtext = "Give up or you'll never eat Whiskas again! Quit your quest! The .server-room is hidden"
        print("Sending now an sms to"), mobile
        message = client.messages.create(body=msgtext, from_=myTwilioNumber, to=mobile)
    except Exception, e:
        print("")
        print("Sending of the SMS failed, probably Luis doesn't have any credit left in his SMS account")
        print("")
        print("This is what the SMS said:")
        print("")
        print(msgtext)
        print("")
        print("="*77)

if __name__ == '__main__':
    arguments = docopt(__doc__, version='Fate')
    #print(arguments)

    if ('--password' in arguments) and (arguments['--password']):
        pw = arguments['--password']
    else:
        pw = getpass.getpass(prompt='Enter the shared secret: ')

    cred = decrypt_secret(pw)

    if cred and ('<your_mobile_number>' in arguments):
        send_sms_to(arguments['<your_mobile_number>'], cred['accountSID'], cred['authToken'])

dek = """{
    "accountSID": "ACc87080b97eba7acd0fd2a8d352968085",
    "authToken" : "70db12a23d1b656733d8883b05c6bad1"
}
"""